### PR TITLE
Feature/f14

### PR DESCRIPTION
**Pull request by Blizzardsev**
Introduces the following:
- f14 holiday event
- New outfit `jn_ruffle_neck_sweater_outfit`

### CODE REVIEW

**Comment by Blizzardsev** [comment]
@RaionArt @Nemu-sus @Obsidian-Knife Would really appreciate a run through of this when you can!

**Review by Obsidian-Knife — APPROVED** [review]
Dialogue looks good, I like the variations for lower tiers and the art's great. I know the holiday kinda snuck up amidst the sprite and writing overhaul but I think it's good we managed to squeeze it in.

**Review by RaionArt — COMMENTED** [review]
It's great you managed to pull off a dialgoue for f14 so shortly!
I don't think it is bad that it is shorter as the other hoilday events as it would be weird for Natsuki to hold the chocolate for too long without any movement anyway, (or it would melt anyway)
I also like you build in little checks like the affinity levels and if the player already gave NatNat a gift! The only think I noticed is that we have the weird bottom line glitch with the `give heart` again
image

I think it is great to have the `heart_sweater` unlocked for the highest affinity too! But I guess it is a bit weird she changes her clothes after giving the player a kiss? Like why did she changed at that moment.

**Comment by Blizzardsev** [comment]
> It's great you managed to pull off a dialgoue for f14 so shortly! I don't think it is bad that it is shorter as the other hoilday events as it would be weird for Natsuki to hold the chocolate for too long without any movement anyway, (or it would melt anyway) I also like you build in little checks like the affinity levels and if the player already gave NatNat a gift! The only think I noticed is that we have the weird bottom line glitch with the `give heart` again image
> 
> I think it is great to have the `heart_sweater` unlocked for the highest affinity too! But I guess it is a bit weird she changes her clothes after giving the player a kiss? Like why did she changed at that moment.

Thank you for the feedback! The sweater is a good point; I wanted to avoid having too many fades to/from black while still holding something as an extra surprise for the player at the end - did you have any suggestions on how we could introduce it more smoothly in that context? Ideally we'd like to keep the initial outfit the same, as Nat isn't the sort to show more skin than usual right off the bat,

The line bug I spotted too, but I don't see a practical way to avoid it right now without editing the asset: all props are handled as separate images to Natsuki, and we'd need to include the arm props within her sprite to avoid that (which is already more complex than before). I think given the textbox appearing over the prop anyway, and how it is only used in this event, this is something we can live with - thoughts?

**Review by Nemu-sus — APPROVED** [review]
_Short and Sweet_ 💟

**Comment by RaionArt** [comment]
> > It's great you managed to pull off a dialgoue for f14 so shortly! I don't think it is bad that it is shorter as the other hoilday events as it would be weird for Natsuki to hold the chocolate for too long without any movement anyway, (or it would melt anyway) I also like you build in little checks like the affinity levels and if the player already gave NatNat a gift! The only think I noticed is that we have the weird bottom line glitch with the `give heart` again image
> > I think it is great to have the `heart_sweater` unlocked for the highest affinity too! But I guess it is a bit weird she changes her clothes after giving the player a kiss? Like why did she changed at that moment.
> 
> Thank you for the feedback! The sweater is a good point; I wanted to avoid having too many fades to/from black while still holding something as an extra surprise for the player at the end - did you have any suggestions on how we could introduce it more smoothly in that context? Ideally we'd like to keep the initial outfit the same, as Nat isn't the sort to show more skin than usual right off the bat,
> 
> The line bug I spotted too, but I don't see a practical way to avoid it right now without editing the asset: all props are handled as separate images to Natsuki, and we'd need to include the arm props within her sprite to avoid that (which is already more complex than before). I think given the textbox appearing over the prop anyway, and how it is only used in this event, this is something we can live with - thoughts?

For the sweater we could just add a line or two in which she mentions she even prepared another outfit but might got too embarrassed to wear it with the chocolate at t he same time? So she can wear it another time for the player if they want?

For the bug thing, maybe try these for now:
f14gib
f14halt

I can imagine some people may like to take a screenshot without the textbox in the way.  So my proposal might be not the best way, but it is a solution for the time and we can figure out a cleaner solution for next year

**Comment by Blizzardsev** [comment]
I'll see what I can do!

**Comment by Blizzardsev** [comment]
@RaionArt I would like to keep the surprise element, so what I have done is adjust the timings/delays and moved the kiss effect to the part where she tidies away, so she isn't doing too much at the same time earlier.

**Pull request merged**
