### PR TITLE
Reworked affinity mechanics

### LINKED ISSUE #138: [ FEATURE REQUEST ] - Affinity/trust freezes
# Overview:
Currently, there exists no daily cap on affinity/trust gains. A cap should be implemented to limit progress and give the relationship between Natsuki and the player time to progress.

Ideally, a means of offering one-time only affinity/trust gains should also be implemented for use by things like events and gifts in the future.

## Must haves:
- Affinity and trust must have a daily cap on gains through repeatable actions (I.E anything via the `relationship()` method).

## Could haves:
- Affinity and trust may have a means of one-time only gains to be used by events, gifts, etc.

## Is this feature request related to a problem? Please describe.
This is a new feature.

### PR DESCRIPTION
**Pull request by Blizzardsev**
- Affinity no longer tied to trust.
- Affinity is now capped daily, and reset daily, limiting the amount it is possible to gain per day,
- Some one-off events now given one-time guaranteed affinity regardless of caps.
- Existing trust-based mechanics for farewells retired.

closes #138

### CODE REVIEW

**Review by Dirrtheif — COMMENTED** [review]
It is not letting me download it

**Review by Dirrtheif — COMMENTED** [review]
It is not letting me download it

**Comment by Blizzardsev** [comment]
> It is not letting me download it

Hi @Dirrtheif - this is a pull request for the affinity rework, where we review the code that is going in to making the changes for affinity. If you're looking to download the mod files, then you will need to do so from here: https://github.com/Just-Natsuki-Team/NatsukiModDev/tree/feature/affinity-adjustments

However, I strongly recommend that you stick to downloading mod files from the master branch as per the installation instructions - this is because any other branch is code that is yet to be reviewed, or undergoing changes and may not be stable.

**Comment by Dirrtheif** [comment]
Ok now how do I switch to it

**Comment by Blizzardsev** [comment]
@Dirrtheif Hiya - if you open a support request then we can go through this in more detail, as this isn't really the place to discuss it.

**Review by multimokia — APPROVED** [review]

**Pull request merged**
