### PR TITLE
Feature/sprite rework

### PR DESCRIPTION
**Pull request by Blizzardsev**
Introduces the following:

- 3 new poses: `arms_crossed_body`, `arms_crossed_desk`, `fingers_on_desk`
- 3 new mouth types: `cat_smug`. `flustered` and `grit_teeth`
- 1 new emote: `smug`
- Implementation of poses into existing dialogue
- Updates to all outfits for new poses
- Adds `sleeves` as an outfit component (referenced by poses and combined with clothing)
- Adds new outfit slots `facewear` and `back`
- Improved handling/checks for empty outfit slots when drawing sprites
- Improved/polished hair sprites for all types
- Improved/polished book props
- Improved/polished ahoges

Outstanding:

_(Note: update refers to varying poses, refresh refers to adding extends, tweaking dialogue, etc.)_

- [x] Update all greetings
- [x] Update all farewells
- [x] Update introduction sequence
- [x] Update idle animations
- [x] Update intro events
- [x] Update holiday events
- [x] Update all regular topics, refresh those where appropriate
- [x] Update Snap dialogue
- [x] Update outfitting dialogue
- [x] Update and refresh compliments
- [x] Update and refresh admissions
- [x] Update and refresh apologies
- [x] Update headpats
- [x] Update weather dialogue
- [x] Update random music dialogue
- [x] Update custom music dialogue

### CODE REVIEW

**Comment by Blizzardsev** [comment]
@Obsidian-Knife @RaionArt - A quick scan through would be awesome if you get a little time! This is a big one, so would appreciate the extra eyes!

**Review by RaionArt — APPROVED** [review]
I really liked the way you let the player interact with Natsuki, when she tried to cheer the player up! Makes the whole conversation feel more natural and it's also nice how it seems like Natsuki takes more time to comfort the player if the admission is more on the sad side. Good job!

**Review by Nemu-sus — APPROVED** [review]
Art looks great
Writing and exp code changes are well done too
👍

**Review by Obsidian-Knife — APPROVED** [review]
The writing changes are good! The added detail and concern displayed by Nat is huge for concern on feelings and I love how previous ones can link with others for continuality!

Having the extended time period options for farewells is great and I love how excited Nat can be in some greetings on the player's return! Very adorable.

**Pull request merged**
