### PR TITLE
Feature/star for new topic indicator

### LINKED ISSUE #679: [ FEATURE REQUEST ] - Star for new topics
Just a simple little yellow star at the top right of each box for new topics or otherwise haven't chosen yet. Could extend into their higher categories to indicate that the player unlocked a topic.

### PR DESCRIPTION
**Pull request by Blizzardsev**
Introduces the following:

- New topics on the menu now have an additional * to indicate they are new/unseen

Closes #679

### CODE REVIEW

**Review by RaionArt — COMMENTED** [review]
Would it be possible to have more of an actual little .png of a star attached to the top corner of the textboxes instead of a "*"?
I feel like that would be a more cute and visual appealing way, which is also more easier to attach than a star in the same text font.

**Comment by RaionArt** [comment]
After thinking about it more, maybe we could reuse the star, we always have at the right bottom corner when dialogue is playing
image
This way it would look more tidier and stays consistent

**Comment by Blizzardsev** [comment]
I'll see what I can do.

**Comment by RaionArt** [comment]
I love the way how clean it looks now! Fantastic job!

**Pull request merged**
