### PR TITLE
Feature/blackjack

### PR DESCRIPTION
**Pull request by Blizzardsev**
Introduces the following:

- New minigame _Blackjack_, available from Affectionate and above once Snap has been unlocked
- New event `event_blackjack_unlock`
- New supporting topics for Blackjack
- Refactored Snap backend code
- Added hotkey information on Settings for Blackjack

### CODE REVIEW

**Comment by Blizzardsev** [comment]
@Just-Natsuki-Team/jn-reviewers This will need heavy testing due to the amount of content/mechanics in the new content being introduced, as well as a brief runthrough of Snap to make sure that all still functions as expected.

**Comment by RaionArt** [comment]
This will need more time to fully review, but some thoughts I already noticed:

When the option is enabled to show the hand total, it should show Nat's counts as well. Maybe something like "5+?" to show the hidden card as well. That would be easier for players who aren't too familiar with the rules of Blackjack or the value of the cards.

With the appearing text at the end of the round it might be nice to make a difference if Natsuki or the player busted for example. I know the notepad shows who won the last round, but still it feels a bit hectic with not an immediately clear way to see to whom the text is directed at.
Possibilities could be different colors, different positions (Like Nat's text appear more on the top), or maybe something added to the text like "Nat busted". Again these are just some suggestions that came to mind, you can choose only one of them or maybe you have an entirely new idea how to handle it.

**Comment by RaionArt** [comment]
image
In this case we hit a draw, but Nat reacted like she won. I feel like we already talked about this problem once already, but it seems like I already pulled the latest version

**Comment by Blizzardsev** [comment]
> This will need more time to fully review, but some thoughts I already noticed:
> 
> When the option is enabled to show the hand total, it should show Nat's counts as well. Maybe something like "5+?" to show the hidden card as well. That would be easier for players who aren't too familiar with the rules of Blackjack or the value of the cards.
> 
> With the appearing text at the end of the round it might be nice to make a difference if Natsuki or the player busted for example. I know the notepad shows who won the last round, but still it feels a bit hectic with not an immediately clear way to see to whom the text is directed at. Possibilities could be different colors, different positions (Like Nat's text appear more on the top), or maybe something added to the text like "Nat busted". Again these are just some suggestions that came to mind, you can choose only one of them or maybe you have an entirely new idea how to handle it.

Sure, I can look at tweaking Nat's text for the hand total option - I agree through that we need to obfuscate the value of her first card still so there's some challenge involved.

With the round ending text, this was more of a placeholder: if possible I'd love to include some better designed graphics with some more flair to show off the result in a more clear/exciting way if time existed for that

**Comment by Blizzardsev** [comment]
> image In this case we hit a draw, but Nat reacted like she won. I feel like we already talked about this problem once already, but it seems like I already pulled the latest version

Very odd, conditions should have handled this. I'll look into it

**Comment by Blizzardsev** [comment]
> image In this case we hit a draw, but Nat reacted like she won. I feel like we already talked about this problem once already, but it seems like I already pulled the latest version

image

This has been added, but the notepaper labels for the names will need extending to reflect this so the text doesn't overrun

**Pull request merged**
