### PR TITLE
Feature/adjust outfit change dialogue

### PR DESCRIPTION
**Pull request by Blizzardsev**
Introduces the following:

- Adjusts outfit change dialogue to better take player closeness into account instead of blanket dialogue for Happy+

### CODE REVIEW

**Review by RaionArt — COMMENTED** [review]
The added dialogue variation are a great way to show the improvement of the relationship with Natsuki! There were two things that came to mind, that are not really changes for the dialogue but maybe some food to think about.

When you select the name of an outfit the names are probably capitalized, for example if we take our custom_outfits "Raionart's gladiolus getup". When Natsuki asks: "Or you want me to wear (outfit)?" she always uses lowercases, so "raionart's" instead of "Raionart's". 
Not a big problem, but it sometimes seems off.

Another point is that I think it would be nice if Natsuki has an extra dialogue if she is already wearing the suggested outfit! It seems a bit jarring that she goes through the same dialogue and "changing", when indeed nothing changes at all. To keep it simple it would be fine to have an additional line for all affinity levels.

**Comment by Blizzardsev** [comment]
> The added dialogue variation are a great way to show the improvement of the relationship with Natsuki! There were two things that came to mind, that are not really changes for the dialogue but maybe some food to think about.
> 
> When you select the name of an outfit the names are probably capitalized, for example if we take our custom_outfits "Raionart's gladiolus getup". When Natsuki asks: "Or you want me to wear (outfit)?" she always uses lowercases, so "raionart's" instead of "Raionart's". Not a big problem, but it sometimes seems off.
> 
> Another point is that I think it would be nice if Natsuki has an extra dialogue if she is already wearing the suggested outfit! It seems a bit jarring that she goes through the same dialogue and "changing", when indeed nothing changes at all. To keep it simple it would be fine to have an additional line for all affinity levels.

Sure, I can look at that

**Comment by Blizzardsev** [comment]
Thinking about it, it would be much cleaner to filter the outfit options so if Nat is already wearing an outfit, it wouldn't appear in the list

**Comment by Blizzardsev** [comment]
Went with a dialogue branch anyway, as then there is no ambiguity that might result from outfit options seemingly being missing

**Review by RaionArt — CHANGES_REQUESTED** [review]
The dialogue seemed to work for me like intended, but after changing to a different outfit afterwards, Natsuki changed the outfit before the screen turned black. I don't think that was the case previously, but I'm not sure

**Comment by Blizzardsev** [comment]
> The dialogue seemed to work for me like intended, but after changing to a different outfit afterwards, Natsuki changed the outfit before the screen turned black. I don't think that was the case previously, but I'm not sure
> 
> Adding to that, Natsuki seems to always swap to a previous outfit before switching to the next one. So for example: Nat wears Outfit 1 Ask her to change to Outfit 2 Switches to Outfit 2 before the blackscreen is fully deployed.
> 
> If asking her to change again Nat wears Outfit 2 Ask her to change to Outfit 3 Switches to Outfit 1 before the blackscreen is fully deployed.

This is Ren'Py sprite handling being absolute jank again. I'll see what I can do

**Comment by Blizzardsev** [comment]
> The dialogue seemed to work for me like intended, but after changing to a different outfit afterwards, Natsuki changed the outfit before the screen turned black. I don't think that was the case previously, but I'm not sure
> 
> Adding to that, Natsuki seems to always swap to a previous outfit before switching to the next one. So for example: Nat wears Outfit 1 Ask her to change to Outfit 2 Switches to Outfit 2 before the blackscreen is fully deployed.
> 
> If asking her to change again Nat wears Outfit 2 Ask her to change to Outfit 3 Switches to Outfit 1 before the blackscreen is fully deployed.

Quick/dirty fix reverting it to how it was. Not great, but it'll do the job

**Review by RaionArt — APPROVED** [review]
Everything seems to work now, thank you for your work!

**Pull request merged**
